export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'

export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'
export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE'
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'

export const CLEAR_DATA = 'CLEAR_DATA'

export const RECIPES_STATE_CHANGE = 'RECIPES_STATE_CHANGE'
export const LIKED_RECIPE_STATE_CHANGE = 'LIKED_RECIPE_STATE_CHANGE'
export const CALENDAR_STATE_CHANGE = 'CALENDAR_STATE_CHANGE'